version: "3.9"
services:
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "dev"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "123"
      POSTGRES_PORT: "5432"
    ports:
      - 54321:5432
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    links:
      - postgres:db
